/**
 * Generator for a native Windows Batch (.bat) diagnostic script
 * Runs actual cmd.exe ping and tracert commands locally on the user's machine
 */
export function generateWindowsCmdBat(targetHost = '108.60.153.162', pingCount = 30): string {
  const cleanHost = targetHost.trim() || '108.60.153.162';

  return `@echo off
:: ==============================================================================
:: WINDOWS COMMAND PROMPT DIAGNOSTIC BATCH SCRIPT
:: Target Host: ${cleanHost}
:: Generated by Google AI Studio PBXware Diagnostic Suite
:: ==============================================================================
title Windows Diagnostic - Ping and Tracert Report for ${cleanHost}
color 0A
cls

set TARGET=${cleanHost}
set DESKTOP=%USERPROFILE%\\Desktop
set REPORT_FILE=%DESKTOP%\\Windows_Cmd_Diagnostic_${cleanHost}.txt

echo ======================================================================
echo   WINDOWS COMMAND PROMPT NATIVE DIAGNOSTIC TOOL
echo   Target Host : %TARGET%
echo   Timestamp   : %DATE% %TIME%
echo   Output File : %REPORT_FILE%
echo ======================================================================
echo.

echo Running Windows Diagnostic for %TARGET%... > "%REPORT_FILE%"
echo Date/Time: %DATE% %TIME% >> "%REPORT_FILE%"
echo ---------------------------------------------------------------------- >> "%REPORT_FILE%"

echo [1/3] Executing Native Windows Ping (%TARGET%, ${pingCount} packets)...
echo [1/3] Executing Native Windows Ping (%TARGET%, ${pingCount} packets)... >> "%REPORT_FILE%"
echo.
ping.exe -n ${pingCount} %TARGET%
ping.exe -n ${pingCount} %TARGET% >> "%REPORT_FILE%"
echo.

echo ----------------------------------------------------------------------
echo [2/3] Executing Native Windows Tracert (tracert -d %TARGET%)...
echo [2/3] Executing Native Windows Tracert (tracert -d %TARGET%)... >> "%REPORT_FILE%"
echo.
tracert.exe -d %TARGET%
tracert.exe -d %TARGET% >> "%REPORT_FILE%"
echo.

echo ----------------------------------------------------------------------
echo [3/3] Executing Pathping for Packet Loss Analysis (%TARGET%)...
echo [3/3] Executing Pathping for Packet Loss Analysis (%TARGET%)... >> "%REPORT_FILE%"
echo.
pathping.exe -n -q 10 %TARGET%
pathping.exe -n -q 10 %TARGET% >> "%REPORT_FILE%"
echo.

echo ======================================================================
echo DIAGNOSTIC COMPLETE!
echo Full report saved to your Desktop:
echo %REPORT_FILE%
echo ======================================================================
echo.
echo Press any key to open the generated report in Notepad...
pause > nul
start notepad.exe "%REPORT_FILE%"
`;
}
