import { PowerShellConfig } from '../types/diagnostic';

export function generatePowerShellScript(config: PowerShellConfig): string {
  const {
    pbxwareIp,
    sipPort,
    rtpRangeStart,
    rtpRangeEnd,
    checkAudioService,
    checkMtu,
    runTracert,
    tracertNoResolve = true,
    pingCount = 30,
  } = config;

  return `# ==============================================================================
# VOIP PBXWARE ENDPOINT DIAGNOSTIC SCRIPT
# Target Server: ${pbxwareIp}
# SIP Port: ${sipPort} | Continuous Ping Count: ${pingCount} | Tracert -d: ${tracertNoResolve ? 'ENABLED (-d)' : 'DISABLED'}
# Generated by VNHA VoIP Network Health Analyzer
# ==============================================================================

#Requires -Version 5.1
[CmdletBinding()]
Param(
    [string]$TargetHost = "${pbxwareIp}",
    [int]$SipPort = ${sipPort},
    [int]$PingCount = ${pingCount},
    [string]$ReportPath = "$([Environment]::GetFolderPath('Desktop'))\\PBXware_Diagnostic_Report.html"
)

Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "  VOIP PBXWARE NETWORK & CONTINUOUS PING DIAGNOSTIC TOOL" -ForegroundColor White
Write-Host "  Target Host: $TargetHost | Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Yellow
Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host ""

$ReportData = @{
    Timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    Target = $TargetHost
    AudioServiceStatus = "UNKNOWN"
    SoundDevices = @()
    PortTests = @()
    MtuSize = 0
    TracertHopCount = 0
    PingPacketsSent = $PingCount
    PingPacketsReceived = 0
    PingLossPercent = 0
}

# ------------------------------------------------------------------------------
# 1. WINDOWS AUDIO SERVICE & HARDWARE AUDIT
# ------------------------------------------------------------------------------
${checkAudioService ? `
Write-Host "[1/5] Checking Windows Audio Service (AudioSrv)..." -ForegroundColor Green
try {
    $AudioSrv = Get-Service -Name "AudioSrv" -ErrorAction Stop
    Write-Host "  -> AudioSrv Status: $($AudioSrv.Status)" -ForegroundColor ($AudioSrv.Status -eq "Running" ? "Green" : "Red")
    $ReportData.AudioServiceStatus = $AudioSrv.Status.ToString()
} catch {
    Write-Host "  -> WARNING: Failed to query Windows Audio Service." -ForegroundColor Yellow
}

Write-Host "Auditing Sound Devices via WMI..." -ForegroundColor Green
try {
    $Devices = Get-CimInstance -ClassName Win32_SoundDevice | Select-Object Name, Status, Manufacturer
    foreach ($dev in $Devices) {
        Write-Host "  -> Device Found: $($dev.Name) [Status: $($dev.Status)]" -ForegroundColor Gray
        $ReportData.SoundDevices += "$($dev.Name) ($($dev.Status))"
    }
} catch {
    Write-Host "  -> Unable to enumerate WMI sound hardware." -ForegroundColor Yellow
}
` : '# Audio service check skipped.'}

# ------------------------------------------------------------------------------
# 2. CONTINUOUS PING TEST (${pingCount} PACKETS)
# ------------------------------------------------------------------------------
Write-Host ""
Write-Host "[2/5] Running Continuous Ping test to $TargetHost (${pingCount} packets)..." -ForegroundColor Green
Write-Host "  -> Executing: ping.exe -n $PingCount $TargetHost" -ForegroundColor Gray
try {
    $PingOutput = ping.exe -n $PingCount $TargetHost
    $PingOutput | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
} catch {
    Write-Host "  -> Execution error running ping.exe." -ForegroundColor Red
}

# ------------------------------------------------------------------------------
# 3. SIP & MEDIA PORT CONNECTIVITY TEST
# ------------------------------------------------------------------------------
Write-Host ""
Write-Host "[3/5] Testing SIP Port Connectivity to $TargetHost..." -ForegroundColor Green

# Test SIP Port
Write-Host "  -> Testing SIP Port $SipPort (TCP/UDP)..." -ForegroundColor Gray
$SipTest = Test-NetConnection -ComputerName $TargetHost -Port $SipPort -WarningAction SilentlyContinue
if ($SipTest.TcpTestSucceeded) {
    Write-Host "  -> [PASS] SIP Port $SipPort is REACHABLE (Latency: $($SipTest.PingReplyDetails.RoundtripTime) ms)" -ForegroundColor Green
    $ReportData.PortTests += "SIP Port $SipPort: OPEN ($($SipTest.PingReplyDetails.RoundtripTime)ms)"
} else {
    Write-Host "  -> [WARNING] SIP Port $SipPort TCP connection failed or filtered." -ForegroundColor Yellow
    $ReportData.PortTests += "SIP Port $SipPort: FILTERED/CLOSED"
}

# Test RTP Sample Ports (${rtpRangeStart}, ${Math.floor((rtpRangeStart + rtpRangeEnd) / 2)}, ${rtpRangeEnd})
$SampleRtpPorts = @(${rtpRangeStart}, ${Math.floor((rtpRangeStart + rtpRangeEnd) / 2)}, ${rtpRangeEnd})
foreach ($port in $SampleRtpPorts) {
    $RtpTest = Test-NetConnection -ComputerName $TargetHost -Port $port -WarningAction SilentlyContinue
    $statusText = if ($RtpTest.PingSucceeded) { "REACHABLE" } else { "CHECKED" }
    Write-Host "  -> Sample Port $port: $statusText" -ForegroundColor Gray
    $ReportData.PortTests += "Port $port: $statusText"
}

# ------------------------------------------------------------------------------
# 4. NETWORK MTU & MSS FRAGMENTATION CHECK
# ------------------------------------------------------------------------------
${checkMtu ? `
Write-Host ""
Write-Host "[4/5] Testing Max Transmission Unit (MTU / MSS Fragmentation)..." -ForegroundColor Green
$MtuFound = 1500
$TestSizes = @(1472, 1450, 1400, 1300)

foreach ($size in $TestSizes) {
    $PingResult = Test-Connection -ComputerName $TargetHost -Count 2 -BufferSize $size -Quiet -ErrorAction SilentlyContinue
    if ($PingResult) {
        $MtuFound = $size + 28 # ICMP Header 28 bytes
        Write-Host "  -> [PASS] Max unfragmented packet size: $MtuFound bytes (Payload: $size bytes)" -ForegroundColor Green
        break
    }
}
$ReportData.MtuSize = $MtuFound
` : '# MTU check skipped.'}

# ------------------------------------------------------------------------------
# 5. NETWORK TRACEROUTE (${tracertNoResolve ? 'tracert -d' : 'tracert'})
# ------------------------------------------------------------------------------
${runTracert ? `
Write-Host ""
Write-Host "[5/5] Running Network Path Route Analysis (${tracertNoResolve ? 'tracert -d' : 'tracert'})..." -ForegroundColor Green
Write-Host "  -> Executing: tracert ${tracertNoResolve ? '-d ' : ''}$TargetHost" -ForegroundColor Gray
try {
    $TracertOutput = tracert ${tracertNoResolve ? '-d ' : ''}$TargetHost
    $TracertOutput | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
} catch {
    Write-Host "  -> Execution error running tracert." -ForegroundColor Red
}
` : '# Traceroute skipped.'}

# ------------------------------------------------------------------------------
# GENERATE HTML DIAGNOSTIC REPORT
# ------------------------------------------------------------------------------
Write-Host ""
Write-Host "Generating Diagnostic HTML Summary on Desktop..." -ForegroundColor Green

$HtmlContent = @"
<!DOCTYPE html>
<html>
<head>
    <title>VOIP PBXware Endpoint Diagnostic Report</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, sans-serif; background-color: #020617; color: #f8fafc; padding: 30px; }
        .card { background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 20px; margin-bottom: 20px; }
        h1 { color: #38bdf8; }
        .pass { color: #4ade80; font-weight: bold; }
        .warn { color: #fbbf24; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid rgba(255,255,255,0.1); padding: 8px 12px; text-align: left; }
        th { background: rgba(56, 189, 248, 0.2); }
    </style>
</head>
<body>
    <h1>PBXware Network & Continuous Ping Diagnostic Report</h1>
    <div class="card">
        <h3>System Overview</h3>
        <p><b>Target PBXware Host:</b> $TargetHost</p>
        <p><b>Scan Timestamp:</b> $($ReportData.Timestamp)</p>
        <p><b>Continuous Ping Count:</b> $PingCount packets</p>
        <p><b>Tracert Mode:</b> ${tracertNoResolve ? 'tracert -d (No DNS Resolution)' : 'Standard Resolution'}</p>
        <p><b>Windows Audio Service:</b> <span class="pass">$($ReportData.AudioServiceStatus)</span></p>
        <p><b>Optimal MTU Size:</b> $($ReportData.MtuSize) bytes</p>
    </div>
    <div class="card">
        <h3>SIP Port Test Results</h3>
        <ul>
            $($ReportData.PortTests | ForEach-Object { "<li>$_</li>" })
        </ul>
    </div>
</body>
</html>
"@

$HtmlContent | Out-File -FilePath $ReportPath -Encoding utf8
Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "  SCAN COMPLETE! Report saved to:" -ForegroundColor Green
Write-Host "  $ReportPath" -ForegroundColor Yellow
Write-Host "======================================================================" -ForegroundColor Cyan
`;
}

